//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int address_id { get; set; }
        public string comment { get; set; }
        public short vote { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Users Users { get; set; }
    }
}
